Repository Floney-2023/Floney-Server, pull requests merged in 2023-09, with the labels that each got.

#149 146 refactor: 테스트 설정 분리
  .github/CODEOWNERS
  .github/workflows/gradle-build.yml
  .github/workflows/gradle.yml
  build.gradle
  src/test/java/com/floney/floney/User/controller/UserControllerTest.java
  src/test/java/com/floney/floney/User/repository/UserRepositoryTest.java
  src/test/resources/application.yaml
Labels: config, hotfix

#150 145 feature 삭제 배치
  build.gradle
  src/main/java/com/floney/floney/FloneyApplication.java
  src/main/java/com/floney/floney/book/entity/BookLine.java
  src/main/java/com/floney/floney/book/entity/BookLineCategory.java
  src/main/java/com/floney/floney/book/entity/BookUser.java
  src/main/java/com/floney/floney/book/entity/Category.java
  src/main/java/com/floney/floney/book/entity/category/BookCategory.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
  src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookService.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/common/DeleteService.java
  src/main/java/com/floney/floney/settlement/domain/entity/Settlement.java
  src/main/java/com/floney/floney/settlement/repository/SettlementCustomRepository.java
  src/main/java/com/floney/floney/settlement/repository/SettlementRepository.java
  src/main/java/com/floney/floney/settlement/repository/SettlementRepositoryImpl.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/repository/UserCustomRepository.java
  src/main/java/com/floney/floney/user/repository/UserRepository.java
  src/main/java/com/floney/floney/user/repository/UserRepositoryImpl.java
  src/main/java/com/floney/floney/user/service/UserService.java
Labels: feature

#159 158 CD 워크플로우 코드 수정
  .github/workflows/gradle.yml
Labels: config, fix

#161 160 refactor fe 추가 요청사항
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/dto/process/DayLineByDayView.java
  src/main/java/com/floney/floney/book/dto/process/DayLineInfo.java
  src/main/java/com/floney/floney/book/dto/process/DayLines.java
  src/main/java/com/floney/floney/book/dto/response/BookInfoResponse.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookService.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/common/DeleteService.java
  src/main/java/com/floney/floney/common/exception/book/AlreadyJoinException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/main/java/com/floney/floney/user/dto/constant/SubscribeStatus.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/service/SubscribeService.java
  src/test/java/com/floney/floney/book/BookServiceTest.java
  src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
Labels: feature

#167 165 feature 월 별 예산자산설정
  src/main/java/com/floney/floney/analyze/dto/process/BookAnalyzer.java
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/dto/request/UpdateAssetRequest.java
  src/main/java/com/floney/floney/book/dto/request/UpdateBudgetRequest.java
  src/main/java/com/floney/floney/book/entity/Asset.java
  src/main/java/com/floney/floney/book/entity/Book.java
  src/main/java/com/floney/floney/book/entity/Budget.java
  src/main/java/com/floney/floney/book/repository/AssetRepository.java
  src/main/java/com/floney/floney/book/repository/BudgetRepository.java
  src/main/java/com/floney/floney/book/service/BookService.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/test/java/com/floney/floney/book/BookFixture.java
Labels: feature, refactor, chore

#168 147 엑셀 라이브러리 추가
  build.gradle
  src/main/java/com/floney/floney/book/controller/ExcelController.java
  src/main/java/com/floney/floney/book/dto/process/MyBookInfo.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/ExcelService.java
  src/main/java/com/floney/floney/book/service/ExcelServiceImpl.java
  src/main/java/com/floney/floney/common/exception/book/ExcelMakingException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
Labels: feature

#179 169 feat: 가계부의 마지막 정산일로부터 며칠이나 지났는 지 조회하는 기능 구현
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/dto/response/LastSettlementDateResponse.java
  src/main/java/com/floney/floney/book/repository/BookCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookRepository.java
  src/main/java/com/floney/floney/book/repository/BookRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookService.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/user/controller/AppleController.java
  src/main/java/com/floney/floney/user/controller/GoogleController.java
  src/main/java/com/floney/floney/user/controller/KakaoController.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/service/AppleUserService.java
  src/main/java/com/floney/floney/user/service/CustomUserDetailsService.java
  src/main/java/com/floney/floney/user/service/GoogleUserService.java
  src/main/java/com/floney/floney/user/service/KakaoUserService.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/User/service/CustomUserDetailsServiceTest.java
  src/test/java/com/floney/floney/User/service/UserServiceTest.java
Labels: feature, refactor

#181 174 refactor 삭제 로직 보완
  src/main/java/com/floney/floney/analyze/dto/response/AnalyzeResponse.java
  src/main/java/com/floney/floney/analyze/entity/BookAnalyze.java
  src/main/java/com/floney/floney/analyze/repository/BookAnalyzeRepository.java
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/entity/Asset.java
  src/main/java/com/floney/floney/book/entity/BookLine.java
  src/main/java/com/floney/floney/book/entity/BookLineCategory.java
  src/main/java/com/floney/floney/book/entity/BookUser.java
  src/main/java/com/floney/floney/book/entity/Budget.java
  src/main/java/com/floney/floney/book/entity/CarryOver.java
  src/main/java/com/floney/floney/book/repository/AssetRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BudgetRepository.java
  src/main/java/com/floney/floney/book/repository/CarryOverCustomRepository.java
  src/main/java/com/floney/floney/book/repository/CarryOverRepository.java
  src/main/java/com/floney/floney/book/repository/CarryOverRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/common/DeleteService.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/settlement/domain/entity/Settlement.java
  src/main/java/com/floney/floney/settlement/repository/SettlementCustomRepository.java
  src/main/java/com/floney/floney/settlement/repository/SettlementRepositoryImpl.java
  src/main/java/com/floney/floney/user/dto/request/LoginRequest.java
  src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
  src/main/java/com/floney/floney/user/dto/request/SubscribeRequest.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/repository/UserCustomRepository.java
  src/main/java/com/floney/floney/user/repository/UserRepository.java
  src/main/java/com/floney/floney/user/repository/UserRepositoryImpl.java
Labels: fix, refactor

#185 183 fix: User의 providerId 길이 255자로 수정
  src/main/java/com/floney/floney/user/entity/User.java
Labels: fix

#189 188 fix: 이메일 인증 코드 불일치 시 에러 코드 변경
  src/main/java/com/floney/floney/book/dto/process/OurBookInfo.java
  src/main/java/com/floney/floney/book/dto/request/CreateBookRequest.java
  src/main/java/com/floney/floney/book/entity/Book.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/user/CodeNotSameException.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/User/service/SubscribeServiceTest.java
  src/test/java/com/floney/floney/book/BookFixture.java
  src/test/java/com/floney/floney/settlement/service/SettlementServiceTest.java
Labels: fix

#192 #190 feat: 간편 회원가입 로직 수정
  src/main/java/com/floney/floney/user/controller/AppleController.java
  src/main/java/com/floney/floney/user/service/AppleUserService.java
  src/main/java/com/floney/floney/user/service/GoogleUserService.java
  src/main/java/com/floney/floney/user/service/KakaoUserService.java
  src/main/java/com/floney/floney/user/service/OAuthUserService.java
  src/main/java/com/floney/floney/user/service/UserService.java
Labels: feature

#197 177 fix: 엑셀 다운로드 및 간편 회원가입 오류 해결
  src/main/java/com/floney/floney/book/controller/ExcelController.java
  src/main/java/com/floney/floney/common/exception/book/ExcelMakingException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/user/controller/AppleController.java
  src/main/java/com/floney/floney/user/controller/GoogleController.java
  src/main/java/com/floney/floney/user/controller/KakaoController.java
Labels: fix

#206 204 feat: 회원 탈퇴 사유 저장
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/main/java/com/floney/floney/common/exception/user/SignoutOtherReasonEmptyException.java
  src/main/java/com/floney/floney/settlement/repository/SettlementRepository.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/constant/SignoutType.java
  src/main/java/com/floney/floney/user/dto/request/SignoutRequest.java
  src/main/java/com/floney/floney/user/entity/SignoutOtherReason.java
  src/main/java/com/floney/floney/user/entity/SignoutReason.java
  src/main/java/com/floney/floney/user/repository/SignoutOtherReasonRepository.java
  src/main/java/com/floney/floney/user/repository/SignoutReasonCustomRepository.java
  src/main/java/com/floney/floney/user/repository/SignoutReasonCustomRepositoryImpl.java
  src/main/java/com/floney/floney/user/repository/SignoutReasonRepository.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/user/controller/UserControllerTest.java
  src/test/java/com/floney/floney/user/repository/SignoutReasonRepositoryTest.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
Labels: feature
