Repository Floney-2023/Floney-Server, pull requests merged in 2023-06, with the labels that each got.

#53 52 feature 가계부 설정
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/dto/OurBookInfo.java
  src/main/java/com/floney/floney/book/dto/OurBookUser.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookService.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/book/util/DateFactory.java
  src/test/java/com/floney/floney/book/BookFixture.java
  src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
  src/test/java/com/floney/floney/book/OurBookUserTest.java
  src/test/java/com/floney/floney/config/UserFixture.java
Labels: feature

#54 17 fix 간편 로그인 방식 수정
  src/main/java/com/floney/floney/common/config/SecurityConfig.java
  src/main/java/com/floney/floney/user/client/GoogleClient.java
  src/main/java/com/floney/floney/user/client/KakaoClient.java
  src/main/java/com/floney/floney/user/dto/constant/Provider.java
  src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
  src/main/java/com/floney/floney/user/dto/response/GoogleUserResponse.java
  src/main/java/com/floney/floney/user/dto/response/KakaoUserResponse.java
  src/main/java/com/floney/floney/user/dto/response/UserResponse.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/repository/UserRepository.java
  src/main/java/com/floney/floney/user/service/GoogleUserService.java
  src/main/java/com/floney/floney/user/service/KakaoUserService.java
  src/test/java/com/floney/floney/User/service/UserServiceTest.java
  src/test/java/com/floney/floney/config/UserFixture.java
Labels: fix

#60 59 test 간편 로그인 테스트 코드 추가
  src/main/java/com/floney/floney/common/exception/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/ErrorType.java
  src/main/java/com/floney/floney/common/exception/OAuthTokenNotValidException.java
  src/main/java/com/floney/floney/user/client/ClientProxy.java
  src/main/java/com/floney/floney/user/client/GoogleClient.java
  src/main/java/com/floney/floney/user/client/KakaoClient.java
  src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/repository/UserRepository.java
  src/main/java/com/floney/floney/user/service/GoogleUserService.java
  src/main/java/com/floney/floney/user/service/KakaoUserService.java
Labels: fix

#62 61 refactor status enum관리하기
  src/main/java/com/floney/floney/book/entity/Book.java
  src/main/java/com/floney/floney/book/entity/BookUser.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/book/service/CategoryServiceImpl.java
  src/main/java/com/floney/floney/common/BaseEntity.java
  src/main/java/com/floney/floney/common/constant/Status.java
  src/main/java/com/floney/floney/user/dto/response/UserResponse.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/repository/UserRepository.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/User/UserRepositoryTest.java
  src/test/java/com/floney/floney/User/service/UserServiceTest.java
  src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
  src/test/java/com/floney/floney/book/BookServiceTest.java
  src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
  src/test/java/com/floney/floney/book/CategoryServiceTest.java
  src/test/java/com/floney/floney/config/WithMockCustomUserSecurityContextFactory.java
Labels: refactor
