Repository Floney-2023/Floney-Server, pull requests merged in 2023-12, with the labels that each got.

#316 #315 : 개발 서버 알람, 실 서버 알람 분리
  src/main/resources/logback-spring.xml
Labels: chore

#317 deploy: 운영 서버 배포
  src/main/resources/logback-spring.xml
Labels: deploy

#323 #313 feat: 서버 상태 확인용 API 구현
  src/main/java/com/floney/floney/common/config/SecurityConfig.java
  src/main/java/com/floney/floney/common/controller/HealthCheckController.java
Labels: feature

#324 #318 fix : Logger 파일 미출력 이슈로 인한 xml 변경
  .gitignore
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-spring.xml
  src/main/resources/slack-error-appender.xml
Labels: fix, infra

#326 #325 fix : 분석 카테고리 조회 시, 이름이 아닌 객체 자체를 쿼리문에 조건으로 지정
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
  src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
Labels: fix

#329 deploy: 운영 서버 배포
  .gitignore
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
  src/main/java/com/floney/floney/common/config/SecurityConfig.java
  src/main/java/com/floney/floney/common/controller/HealthCheckController.java
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-spring.xml
  src/main/resources/slack-error-appender.xml
  src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
Labels: deploy

#331 #330 docs: 이슈 & PR 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/fix_request.md
  .github/ISSUE_TEMPLATE/hotfix_request.md
  .github/ISSUE_TEMPLATE/release_request.md
  .github/pull_request_template.md
Labels: docs, config

#320 #319 hotfix: 자산 삭제 시 에러 해결
  src/main/java/com/floney/floney/analyze/service/AssetService.java
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/BookDeletedEventHandler.java
  src/main/java/com/floney/floney/book/domain/entity/Asset.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/dto/constant/CategoryEnum.java
  src/main/java/com/floney/floney/book/dto/response/BookLineResponse.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/floney/floney/book/MonthLineResponseTest.java
  src/test/java/com/floney/floney/fixture/BookLineFixture.java
  src/test/resources/application.yaml
Labels: hotfix

#336 #335 hotfix: 자산 upsert 쿼리에서 테이블 이름을 소문자로 변경
  src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
Labels: hotfix

#334 deploy: 개발 서버 업데이트
  .github/workflows/main-cd.yml
  src/main/java/com/floney/floney/analyze/service/AssetService.java
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/BookDeletedEventHandler.java
  src/main/java/com/floney/floney/book/domain/entity/Asset.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/dto/constant/CategoryEnum.java
  src/main/java/com/floney/floney/book/dto/response/BookLineResponse.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/floney/floney/book/MonthLineResponseTest.java
  src/test/java/com/floney/floney/fixture/BookLineFixture.java
  src/test/resources/application.yaml
Labels: deploy

#340 #339 hotfix: OUTCOME인 내역은 자산을 (-)로 추가하도록 수정
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
Labels: hotfix

#345 #334 hotfix: subtractAssetOf 메서드에서 부호가 반대로 연산되던 문제 수정
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
Labels: hotfix

#341 deploy: main → develop
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
Labels: deploy

#346 #342 hotfix : 카테고리 중복 생성 방지 검사 추가
  src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
  src/main/java/com/floney/floney/common/exception/book/AlreadyExistException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
Labels: hotfix

#352 deploy: main → develop
  src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
  src/main/java/com/floney/floney/common/exception/book/AlreadyExistException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
Labels: deploy

#350 #321 feat: 모니터링 서버 구축
  build.gradle
  src/main/java/com/floney/floney/common/config/SecurityConfig.java
Labels: config, feature
