Repository Floney-2023/Floney-Server, pull requests merged in 2023-11, with the labels that each got.

#229 #228 fix: cross join이 발생하는 쿼리 수정
  src/main/java/com/floney/floney/book/dto/request/DeleteCategoryRequest.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/CarryOverCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/category/BookLineCategoryRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepositoryImpl.java
Labels: fix

#235 #226 fix: 비밀번호 재발급 시 유효성 검증 로직 추가
  src/main/java/com/floney/floney/common/domain/vo/Mail.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/main/java/com/floney/floney/common/exception/user/NotEmailUserException.java
  src/main/java/com/floney/floney/common/util/MailProvider.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/domain/vo/RegeneratePasswordMail.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/repository/UserRepository.java
  src/main/java/com/floney/floney/user/service/AuthenticationService.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
  src/test/java/com/floney/floney/fixture/UserFixture.java
  src/test/java/com/floney/floney/user/controller/UserControllerTest.java
  src/test/java/com/floney/floney/user/service/AuthenticationServiceTest.java
  src/test/java/com/floney/floney/user/service/SubscribeServiceTest.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
Labels: fix, feature

#253 #251 chore: 빌드 시 logs 폴더 추가
  .github/workflows/gradle.yml
Labels: config

#264 #263 refactor: 회원 가입 및 회원 탈퇴 API 엔드포인트 수정
  src/main/java/com/floney/floney/common/config/SecurityConfig.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/test/java/com/floney/floney/user/controller/UserControllerTest.java
Labels: test, refactor

#272 #267 비밀번호 변경 API 에러 수정
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/request/UpdatePasswordRequest.java
  src/main/java/com/floney/floney/user/service/AuthenticationService.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/user/service/AuthenticationServiceTest.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
Labels: fix

#270 269 feature 방장 탈퇴시 위임로직 추가
  src/main/java/com/floney/floney/book/domain/entity/Book.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/user/service/UserService.java
Labels: feature

#271 266 feature 카테고리 삭제 시 전체 내역 삭제 & 분석 현재 자산 값 변경
  src/main/java/com/floney/floney/analyze/dto/process/BookAnalyzer.java
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepository.java
  src/main/java/com/floney/floney/book/repository/category/CategoryCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
  src/test/java/com/floney/floney/book/CategoryRepositoryTest.java
Labels: feature, refactor

#285 #268 feat: 정산 API에 요청자가 가계부 유저인지 검사하는 로직 추가
  src/main/java/com/floney/floney/settlement/controller/SettlementController.java
  src/main/java/com/floney/floney/settlement/service/SettlementService.java
  src/test/java/com/floney/floney/settlement/service/SettlementServiceTest.java
Labels: feature

#288 #277 fix: 회원탈퇴 시 provider id 삭제 안되던 오류 수정
  src/main/java/com/floney/floney/user/entity/User.java
Labels: fix

#284 283 feature 가계부 나가기 시 모든 내역 삭제
  src/main/java/com/floney/floney/analyze/service/AssetService.java
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/BookDeletedEventHandler.java
  src/main/java/com/floney/floney/analyze/service/CarryOverService.java
  src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/event/BookLineDeletedEvent.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookUserCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/book/service/category/CategoryService.java
  src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
  src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepositoryImpl.java
  src/main/java/com/floney/floney/settlement/service/BookDeletedEventHandler.java
Labels: fix, feature

#291 #290 feat: 회원 마케팅 수신 동의 여부 조회 API 구현
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/response/ReceiveMarketingResponse.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
Labels: feature

#289 #275 feat: 비밀번호 확인 API 구현
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/request/PasswordAuthenticateRequest.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/service/AuthenticationService.java
  src/test/java/com/floney/floney/user/controller/UserControllerTest.java
Labels: feature

#294 #293 fix : 이체 내역이라면 이월,자산 반영 X
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
Labels: fix

#296 #292 feature: 회원탈퇴 API 응답 추가
  src/main/java/com/floney/floney/book/repository/BookCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookCustomRepositoryImpl.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/response/SignoutResponse.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/fixture/BookFixture.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
Labels: feature

#295 293 fix 가계부 초기화 시 자산 초기화
  src/main/java/com/floney/floney/analyze/service/AssetService.java
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/CarryOverService.java
  src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/domain/entity/Asset.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
  src/main/java/com/floney/floney/book/dto/request/BookLineRequest.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverRepository.java
  src/main/java/com/floney/floney/book/service/BookLineService.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/book/service/category/CategoryFactory.java
  src/test/java/com/floney/floney/fixture/BookLineFixture.java
Labels: fix

#298 #297 fix: 회원 비밀번호 검사 API http method 변경
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/test/java/com/floney/floney/user/controller/UserControllerTest.java
Labels: fix

#300 #299 fix: 정산 에러 핸들러 추가
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/main/java/com/floney/floney/common/exception/common/NotSubscribeException.java
  src/main/java/com/floney/floney/common/exception/settlement/SettlementNotFoundException.java
  src/main/java/com/floney/floney/common/exception/user/NotFoundSubscribeException.java
  src/main/java/com/floney/floney/common/exception/user/SubscribeException.java
  src/main/java/com/floney/floney/settlement/service/SettlementService.java
Labels: fix

#301 #265 chore: exception 발생 시 로그 형식 변경
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
Labels: chore

#287 #286 main 브랜치 CD 설정 & 기타 설정 수정
  .github/workflows/develop-cd.yml
  .github/workflows/gradle-build.yml
  .github/workflows/main-cd.yml
  script/start.sh
  script/stop.sh
Labels: config, chore

#304 #303 hotfix: 운영 start.sh 파일 저장 방식 변경
  .github/workflows/main-cd.yml
Labels: hotfix

#312 #311 fix: 현재 서비스 프로세스 id 찾는 명령어 수정
  script/stop.sh
Labels: config, fix

#310 deploy: 운영 서버 배포
  script/stop.sh
  src/main/resources/logback-spring.xml
Labels: deploy
