Repository Floney-2023/Floney-Server, pull requests merged in 2024-07, with the labels that each got.

#488 #487 fix: 정산 세부 내역 조회 시, 비활성화 유저 처리
  .github/CODEOWNERS
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/settlement/dto/response/SettlementResponse.java
  src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepository.java
  src/main/java/com/floney/floney/settlement/repository/SettlementUserCustomRepositoryImpl.java
  src/main/java/com/floney/floney/settlement/repository/SettlementUserRepository.java
  src/main/java/com/floney/floney/settlement/service/SettlementService.java
Labels: fix

#486 #485 hotfix: budget 에 유니크 인덱스 추가
  src/main/resources/db/migration/mysql/V18__add_unique_index_in_budget.sql
Labels: hotfix

#489 deploy: main → develop
  src/main/resources/db/migration/mysql/V18__add_unique_index_in_budget.sql
Labels: deploy

#494 #492 hotfix : 반복 내역 삭제 로직 수정
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
Labels: hotfix

#496 deploy : main -> develop
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
Labels: deploy

#498 #497 chore: 배포 설정 수정
  .github/CODEOWNERS
  .github/workflows/main-cd.yml
  script/start.sh
  script/stop.sh
Labels: config

#499 #497 chore: 변경된 ec2 설정에 따라 `appspec.yml` 수정
  appspec.yml
Labels: config

#500 #497 chore: CD 설정 해결
  appspec.yml
Labels: config

#501 #497 chore: 상대 경로 수정
  appspec.yml
Labels: config

#502 #497 chore: 상대 경로 수정
  script/start.sh
  script/stop.sh
Labels: config
