Repository Floney-2023/Floney-Server, pull requests merged in 2024-05, with the labels that each got.

#455 #439 feat: 즐겨찾기 추가 구현
  src/main/java/com/floney/floney/book/controller/FavoriteController.java
  src/main/java/com/floney/floney/book/domain/entity/Book.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/domain/favorite/Favorite.java
  src/main/java/com/floney/floney/book/dto/request/FavoriteCreateRequest.java
  src/main/java/com/floney/floney/book/dto/response/FavoriteResponse.java
  src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
  src/main/java/com/floney/floney/book/service/FavoriteService.java
  src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
  src/main/java/com/floney/floney/common/exception/book/FavoriteSizeInvalidException.java
  src/main/java/com/floney/floney/common/exception/book/NotFoundBookUserException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/main/resources/db/migration/mysql/V16__add_favorite.sql
  src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/fixture/FavoriteApiFixture.java
  src/test/resources/clear.sql
Labels: feature

#452 #450 feature: 반복 기준에 맞는 내역 생성
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/util/DateUtil.java
  src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
  src/test/java/com/floney/floney/fixture/BookRequestDtoFixture.java
Labels: feature

#463 #462 feat: 즐겨찾기 조회
  src/main/java/com/floney/floney/book/controller/FavoriteController.java
  src/main/java/com/floney/floney/book/domain/category/CategoryType.java
  src/main/java/com/floney/floney/book/domain/category/entity/Category.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
  src/main/java/com/floney/floney/book/service/FavoriteService.java
  src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
  src/main/java/com/floney/floney/common/exception/book/FavoriteNotFoundException.java
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/fixture/FavoriteApiFixture.java
Labels: test, feature

#467 #466 feat: 즐겨찾기 삭제
  src/main/java/com/floney/floney/book/controller/FavoriteController.java
  src/main/java/com/floney/floney/book/service/FavoriteService.java
  src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
  src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
Labels: feature

#461 #460 feat: 가계부 삭제, 카테고리 삭제 시 즐겨찾기 삭제
  src/main/java/com/floney/floney/book/repository/favorite/FavoriteCustomRepository.java
  src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
  src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
  src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/CategoryAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/fixture/FavoriteApiFixture.java
Labels: feature

#469 #468 feat: 즐겨찾기 개수 제한을 카테고리 당 5개로 수정
  src/main/java/com/floney/floney/book/domain/category/entity/Category.java
  src/main/java/com/floney/floney/book/domain/entity/Book.java
  src/main/java/com/floney/floney/book/repository/favorite/FavoriteRepository.java
  src/main/java/com/floney/floney/book/service/FavoriteServiceImpl.java
  src/main/java/com/floney/floney/common/exception/book/FavoriteSizeInvalidException.java
  src/test/java/com/floney/floney/acceptance/FavoriteAcceptanceTest.java
Labels: feature

#471 #470 feat: 임시 비밀번호 길이 수정
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/service/UserService.java
Labels: feature

#476 fix: 태국화폐 변경
  src/main/java/com/floney/floney/book/domain/Currency.java
Labels: fix

#474 fix: 반복 내역 주말 날짜 선택 후 평일에만 날짜 조정되도록 수정
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
Labels: fix
