Repository Floney-2023/Floney-Server, pull requests merged in 2024-01, with the labels that each got.

#354 #353 refactor : AlreadyExistException 로그 메세지, 레벨 수정
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
Labels: fix

#360 #359 배포 명령어 수정
  script/start.sh
Labels: config, fix

#361 #357 feature: 비밀번호 최대 길이 변경
  .github/workflows/gradle-build.yml
  build.gradle
  src/main/java/com/floney/floney/common/config/SecurityConfig.java
  src/main/java/com/floney/floney/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/request/SignupRequest.java
  src/main/java/com/floney/floney/user/entity/User.java
  src/main/java/com/floney/floney/user/service/AuthenticationService.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/acceptance/UserAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/config/AcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/config/IntegrationTestExecutionListener.java
  src/test/java/com/floney/floney/acceptance/fixture/BookApiFixture.java
  src/test/java/com/floney/floney/acceptance/fixture/UserApiFixture.java
  src/test/java/com/floney/floney/book/BookLineRepositoryTest.java
  src/test/java/com/floney/floney/book/BookServiceTest.java
  src/test/java/com/floney/floney/book/BookUserRepositoryTest.java
  src/test/java/com/floney/floney/fixture/UserFixture.java
  src/test/java/com/floney/floney/user/entity/UserTest.java
  src/test/java/com/floney/floney/user/repository/UserRepositoryTest.java
  src/test/java/com/floney/floney/user/service/AuthenticationServiceTest.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
  src/test/resources/application.yaml
  src/test/resources/clear.sql
Labels: test, feature

#372 #368 refactor: logger 파일 보완
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/logback-spring.xml
Labels: config, refactor

#371 #366 feat: 비밀번호 변경 제한 추가
  src/main/java/com/floney/floney/common/config/RedisConfig.java
  src/main/java/com/floney/floney/common/util/RedisProvider.java
  src/main/java/com/floney/floney/user/infrastructure/PasswordHistoryManagerImpl.java
  src/main/java/com/floney/floney/user/service/PasswordHistoryManager.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/acceptance/config/IntegrationTestExecutionListener.java
  src/test/java/com/floney/floney/fixture/UserFixture.java
  src/test/java/com/floney/floney/user/service/PasswordHistoryManagerTest.java
  src/test/java/com/floney/floney/user/service/UserServiceTest.java
Labels: test, feature

#375 #367 fix : 엑셀 date포맷으로 날짜 추출 변경
  src/main/java/com/floney/floney/book/service/ExcelServiceImpl.java
Labels: fix

#377 #376 feat : 엑셀 추출 범위(작년) 추가
  src/main/java/com/floney/floney/book/domain/constant/ExcelDuration.java
  src/main/java/com/floney/floney/common/domain/vo/DateDuration.java
Labels: feature

#379 #378 feat : 엑셀 추출 시 최근 날짜부터 정렬
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/ExcelServiceImpl.java
Labels: feature

#381 #380 fix: 비밀번호 변경 시 현재 비밀번호도 검증
  src/main/java/com/floney/floney/common/exception/common/ErrorControllerAdvice.java
  src/main/java/com/floney/floney/common/exception/common/ErrorType.java
  src/main/java/com/floney/floney/common/exception/user/PasswordNotSameException.java
  src/main/java/com/floney/floney/user/controller/UserController.java
  src/main/java/com/floney/floney/user/dto/request/UpdatePasswordRequest.java
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/acceptance/UserAcceptanceTest.java
Labels: fix

#385 #384 fix : User inactive() 이전, User 탈퇴 이벤트 시행
  src/main/java/com/floney/floney/user/entity/User.java
Labels: fix

#386 deploy: develop → main
  src/main/java/com/floney/floney/user/entity/User.java
Labels: deploy
