Repository Floney-2023/Floney-Server, pull requests merged in 2024-03, with the labels that each got.

#402 #401 refactor : 일별 내역 조회 시, 반복 내역 조회
  src/main/java/com/floney/floney/book/domain/RepeatDuration.java
  src/main/java/com/floney/floney/book/domain/entity/RepeatBookLine.java
  src/main/java/com/floney/floney/book/dto/process/BookLineWithWriterView.java
  src/main/java/com/floney/floney/book/dto/response/RepeatBookLineResponse.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/fixture/BookApiFixture.java
  src/test/java/com/floney/floney/book/domain/entity/RepeatBookLineTest.java
Labels: feature

#404 #403 feat: 비밀번호 변경 조건 삭제
  .github/CODEOWNERS
  .github/workflows/gradle-build.yml
  src/main/java/com/floney/floney/user/service/UserService.java
  src/test/java/com/floney/floney/user/service/PasswordHistoryManagerTest.java
  src/test/resources/application.yaml
Labels: feature

#408 #407 fix: 이월설정 동시성 처리
  src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverRepository.java
  src/main/resources/db/migration/mysql/V12__add_unique_key_in_carry_over.sql
  src/test/java/com/floney/floney/book/service/CarryOverServiceTest.java
Labels: fix

#417 #416 fix: unique index 가 걸린 데이터에 중복된 논리 삭제 해결
  src/main/java/com/floney/floney/book/controller/BookController.java
  src/main/java/com/floney/floney/book/domain/category/entity/Category.java
  src/main/java/com/floney/floney/book/dto/response/BookLineResponse.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/category/CategoryRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/test/java/com/floney/floney/FloneyApplicationTests.java
  src/test/java/com/floney/floney/acceptance/BookAcceptanceTest.java
  src/test/java/com/floney/floney/acceptance/fixture/BookApiFixture.java
  src/test/java/com/floney/floney/book/service/BookLineServiceTest.java
  src/test/java/com/floney/floney/fixture/BookLineCategoryFixture.java
  src/test/java/com/floney/floney/fixture/BookLineFixture.java
  src/test/java/com/floney/floney/fixture/CategoryFixture.java
  src/test/java/com/floney/floney/fixture/SubcategoryFixture.java
Labels: fix

#419 #415 feature: 가계부 초기화, 가계부 나가기 시 반복 내역 삭제
  src/main/java/com/floney/floney/book/repository/RepeatBookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/RepeatBookLineRepository.java
  src/main/java/com/floney/floney/book/repository/RepeatBookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/test/java/com/floney/floney/book/repository/RepeatBookLineRepositoryTest.java
  src/test/java/com/floney/floney/fixture/BookLineFixture.java
  src/test/java/com/floney/floney/fixture/RepeatBookLineFixture.java
  src/test/java/com/floney/floney/fixture/SubcategoryFixture.java
Labels: feature

#421 #420 fix: 자산에서 제외 기능이 비정상 동작
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/test/java/com/floney/floney/book/domain/entity/BookLineTest.java
  src/test/java/com/floney/floney/book/domain/entity/RepeatBookLineTest.java
Labels: fix, hotfix

#423 #422 fix : 반복문 자산 반환 기간 조건 수정
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
Labels: fix

#426 #425 refactor: 내역 조회 시 이월 설정 계산
  src/main/java/com/floney/floney/analyze/service/BookDeletedEventHandler.java
  src/main/java/com/floney/floney/analyze/service/CarryOverService.java
  src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/domain/entity/CarryOver.java
  src/main/java/com/floney/floney/book/dto/process/CarryOverInfo.java
  src/main/java/com/floney/floney/book/repository/CarryOverJdbcRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/CarryOverRepository.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/resources/db/migration/mysql/V13__delete_carry_over.sql
  src/test/java/com/floney/floney/book/domain/entity/CarryOverTest.java
  src/test/java/com/floney/floney/book/repository/BookLineCustomRepositoryTest.java
  src/test/java/com/floney/floney/book/service/CarryOverServiceTest.java
  src/test/resources/clear.sql
Labels: refactor

#429 #427 refactor: 자산 로직 변경
  src/main/java/com/floney/floney/analyze/dto/process/BookAnalyzer.java
  src/main/java/com/floney/floney/analyze/dto/request/AnalyzeRequestByAsset.java
  src/main/java/com/floney/floney/analyze/dto/response/AnalyzeResponseByAsset.java
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/AssetService.java
  src/main/java/com/floney/floney/analyze/service/AssetServiceImpl.java
  src/main/java/com/floney/floney/analyze/service/BookDeletedEventHandler.java
  src/main/java/com/floney/floney/analyze/service/CarryOverServiceImpl.java
  src/main/java/com/floney/floney/analyze/vo/Assets.java
  src/main/java/com/floney/floney/book/domain/entity/Asset.java
  src/main/java/com/floney/floney/book/domain/entity/BookLine.java
  src/main/java/com/floney/floney/book/dto/process/AssetInfo.java
  src/main/java/com/floney/floney/book/repository/AssetJdbcRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineCustomRepository.java
  src/main/java/com/floney/floney/book/repository/BookLineRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepository.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetCustomRepositoryImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/AssetRepository.java
  src/main/java/com/floney/floney/book/service/BookLineServiceImpl.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
  src/main/resources/db/migration/mysql/V14__drop_asset.sql
  src/test/java/com/floney/floney/analyze/vo/AssetsTest.java
  src/test/java/com/floney/floney/book/service/AssetServiceTest.java
  src/test/java/com/floney/floney/book/service/BookLineServiceTest.java
  src/test/resources/clear.sql
Labels: refactor

#432 #430 fix: Subcategory 추가 및 삭제 에러 해결
  src/main/java/com/floney/floney/book/repository/category/SubcategoryCustomRepository.java
  src/main/java/com/floney/floney/book/repository/category/SubcategoryRepository.java
  src/main/java/com/floney/floney/book/repository/category/SubcategoryRepositoryImpl.java
  src/main/java/com/floney/floney/book/service/category/CategoryServiceImpl.java
  src/test/java/com/floney/floney/book/repository/category/SubcategoryRepositoryTest.java
Labels: fix

#433 #431 fix : 예산 조회 시, ACTIVE만 조회 조건 추가
  src/main/java/com/floney/floney/book/repository/analyze/BudgetCustomRepositoryImpl.java
Labels: fix

#435 #434 fix : 예산 조회 시, ACTIVE 조건 추가
  src/main/java/com/floney/floney/analyze/service/AnalyzeServiceImpl.java
  src/main/java/com/floney/floney/book/repository/analyze/BudgetRepository.java
  src/main/java/com/floney/floney/book/service/BookServiceImpl.java
Labels: fix

#437 #436 fix: `book.code` 에 인덱스 추가
  src/main/resources/db/migration/mysql/V15__add_index_in_book.sql
  src/test/java/com/floney/floney/book/service/BookServiceTest.java
  src/test/java/com/floney/floney/fixture/BookFixture.java
Labels: fix

#440 #314 docs : readme 추가
  README.md
  erd.png
  system_architecture.png
Labels: docs

#447 #445 hotfix: 마이페이지의 내 가계부 팀원 수 에러 해결
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/test/java/com/floney/floney/book/repository/BookUserCustomRepositoryTest.java
Labels: test, hotfix

#448 release: main → develop
  src/main/java/com/floney/floney/book/repository/BookUserRepositoryImpl.java
  src/test/java/com/floney/floney/book/repository/BookUserCustomRepositoryTest.java
Labels: deploy

#443 #441 feat : 화폐 단위 추가
  src/main/java/com/floney/floney/book/domain/Currency.java
Labels: feature
